import { ThemeProvider } from '@/app/providers/ThemeProvider';
import '@/app/styles/index.scss';
import { locales } from '@/shared/config/i18n/config';
import clsx from 'clsx';
import { Metadata } from 'next';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import { getTranslations } from 'next-intl/server';
import { Inter } from 'next/font/google';
import { ReactNode, Suspense } from 'react';

const inter = Inter({ subsets: ['latin'] });

type RootLayoutProps = {
	children: ReactNode;
	params: { locale: string };
};

export function generateStaticParams() {
	return locales.map((locale) => ({ locale }));
}

export async function generateMetadata({
	params: { locale },
}: Omit<RootLayoutProps, 'children'>) {
	const t = await getTranslations({ locale });

	const metadata: Metadata = {
		title: t('RootLayout.title'),
		description: 'Generated by create next app',
	};

	return metadata;
}

export default function RootLayout({
	children,
	params: { locale },
}: RootLayoutProps) {
	const messages = useMessages();

	return (
		<html lang={locale}>
			<body className={clsx(inter.className, 'flex h-full flex-col')}>
				<NextIntlClientProvider locale={locale} messages={messages}>
					<ThemeProvider>
						<Suspense fallback=''>{children}</Suspense>
					</ThemeProvider>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
