import { ThemeProvider } from 'app/providers/ThemeProvider';
import type { Metadata } from 'next';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import { Inter } from 'next/font/google';
import { ReactNode, Suspense } from 'react';
// import 'shared/config/i18n/i18n';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
	params: { locale },
}: Readonly<{
	children: ReactNode;
	params: { locale: string };
}>) {
	const messages = useMessages();

	return (
		<html lang={locale}>
			<body className={inter.className}>
				<NextIntlClientProvider locale={locale} messages={messages}>
					<ThemeProvider>
						<Suspense fallback=''>{children}</Suspense>
					</ThemeProvider>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
